In [1]:
import numpy as np 
import pandas as pd

In [2]:
## series of 1-D array

In [61]:
s = pd.Series([10,20,30,40]) 
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [62]:
pop = pd.Series([1444,1393,323,278],
               index = ["India", "China","USA","Indonesia"],
                        name = "population_millions")

print(pop)

India        1444
China        1393
USA           323
Indonesia     278
Name: population_millions, dtype: int64

In [63]:
print(pop[pop>500])

India    1444
China    1393
Name: population_millions, dtype: int64

In [64]:
q1 = pd.Series({"laptop":120, "phones":340, "tables":77})
q2 = pd.Series({"phones":44, "laptops":474, "watches":73})
print(q1,q2)

laptop    120
phones    340
tables     77
dtype: int64 phones      44
laptops    474
watches     73
dtype: int64

In [65]:
## Data Frame

In [66]:
df = pd.DataFrame({
    "name": ["tharun", "kumar", "Akhil", "Varma", "Kushal"],
    "dept": ["IT", "HR", "IT", "Finance", "HR"],
    "salary": [52000, 48000, 47000, 75000, 50000],
    "city": ["Vizag", "Hyderabad", "Mumbai", "Chennai", "Bangalor"]
})
print(df)

     name     dept  salary       city
0  tharun       IT   52000      Vizag
1   kumar       HR   48000  Hyderabad
2   Akhil       IT   47000     Mumbai
3   Varma  Finance   75000    Chennai
4  Kushal       HR   50000   Bangalor

In [67]:
print(df)
print(list(df.columns))
print(df.head())
df.info()
df.describe()

     name     dept  salary       city
0  tharun       IT   52000      Vizag
1   kumar       HR   48000  Hyderabad
2   Akhil       IT   47000     Mumbai
3   Varma  Finance   75000    Chennai
4  Kushal       HR   50000   Bangalor
['name', 'dept', 'salary', 'city']
     name     dept  salary       city
0  tharun       IT   52000      Vizag
1   kumar       HR   48000  Hyderabad
2   Akhil       IT   47000     Mumbai
3   Varma  Finance   75000    Chennai
4  Kushal       HR   50000   Bangalor
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   dept    5 non-null      object
 2   salary  5 non-null      int64
 3   city    5 non-null      object
dtypes: int64(1), object(3)
memory usage: 292.0+ bytes

             salary
count      5.000000
mean   54400.000000
std    11674.759098
min    47000.000000
25%    48000.000000
50%    50000.000000
75%    52000.000000
max    75000.000000

In [68]:
raw = pd.DataFrame({
    "order_id": ["1001", "1002", "1003"],
    "amount": ["2500", "1800", "3200"]
})

print(raw["amount"].sum())

250018003200

In [69]:
clean = raw.copy()

In [70]:
clean["order_id"] = pd.to_numeric(clean["order_id"])
clean["amount"] = pd.to_numeric(clean["amount"])

In [71]:
print(clean["amount"].sum())

7500

In [72]:
df

     name     dept  salary       city
0  tharun       IT   52000      Vizag
1   kumar       HR   48000  Hyderabad
2   Akhil       IT   47000     Mumbai
3   Varma  Finance   75000    Chennai
4  Kushal       HR   50000   Bangalor

In [73]:
people = df.set_index("name")

In [74]:
people

           dept  salary       city
name
tharun       IT   52000      Vizag
kumar        HR   48000  Hyderabad
Akhil        IT   47000     Mumbai
Varma   Finance   75000    Chennai
Kushal       HR   50000   Bangalor

In [75]:
print(people.loc["tharun"])

dept         IT
salary    52000
city      Vizag
Name: tharun, dtype: object

In [76]:
print(people.loc[["tharun"], ["salary"]])

        salary
name
tharun   52000

In [77]:
print(people.iloc[1])

dept             HR
salary        48000
city      Hyderabad
Name: kumar, dtype: object

In [78]:
print(people.iloc[0:3], [0,2])

       dept  salary       city
name
tharun   IT   52000      Vizag
kumar    HR   48000  Hyderabad
Akhil    IT   47000     Mumbai [0, 2]

In [79]:
print(people[people["salary"] < 49000])

      dept  salary       city
name
kumar   HR   48000  Hyderabad
Akhil   IT   47000     Mumbai

In [80]:
print(people[(people["dept"] == "IT") & (people["salary"] < 49000)])

      dept  salary    city
name
Akhil   IT   47000  Mumbai

In [86]:
print(people.query("dept == 'IT' and salary < 49000"))

      dept  salary    city
name
Akhil   IT   47000  Mumbai

In [ ]:
print(people.query("dept == 'IT'"))

In [89]:
messy = pd.DataFrame({
    "product": ["Pen", "Book", "Bag", "Lamp", "Mug"],
    "Price": [28, np.nan, 850, 1200, np.nan],
    "rating": [4.1, 4.5, np.nan, 8.6, 5.5]
})

# Corrected: Use the same variable name that was defined above
messy

  product   Price  rating
0     Pen    28.0     4.1
1    Book     NaN     4.5
2     Bag   850.0     NaN
3    Lamp  1200.0     8.6
4     Mug     NaN     5.5

In [90]:
messy.isna().sum()

product    0
Price      2
rating     1
dtype: int64

In [91]:
filled = messy.copy()

In [92]:
filled = messy.copy()  
filled["Price"] = filled["Price"].fillna(filled["Price"].mean())

In [93]:
filled["rating"] = filled["rating"].fillna(filled["rating"].median())

In [94]:
print(filled)

  product        Price  rating
0     Pen    28.000000     4.1
1    Book   692.666667     4.5
2     Bag   850.000000     5.0
3    Lamp  1200.000000     8.6
4     Mug   692.666667     5.5

In [95]:
print(people)

           dept  salary       city
name
tharun       IT   52000      Vizag
kumar        HR   48000  Hyderabad
Akhil        IT   47000     Mumbai
Varma   Finance   75000    Chennai
Kushal       HR   50000   Bangalor